/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package FizikselYer;

import YonetimSistemi.YonetimSistemi;
import javax.swing.JOptionPane;
import magazaekleme.VeriTabani;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author User
 */
public class FizikselYer extends javax.swing.JFrame {

    /**
     * Creates new form FizikselYer
     */
    private VeriTabani veriTabani = new VeriTabani();
    private String sql = "";
    private YonetimSistemi yonetimSistemi;
    
    public FizikselYer() {
        veriTabani.BaglantiyiYap();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblTeklifFisiSaklamaYeri = new javax.swing.JLabel();
        txtTeklifFisiSaklamaYeriAdi = new javax.swing.JTextField();
        btnKaydet = new javax.swing.JButton();
        btnListele = new javax.swing.JButton();
        btnKapat = new javax.swing.JButton();
        btnSil = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblFizikselYer = new javax.swing.JTable();

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setName("jTable1"); // NOI18N
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(magazaekleme.MagazaEklemeApp.class).getContext().getResourceMap(FizikselYer.class);
        lblTeklifFisiSaklamaYeri.setText(resourceMap.getString("lblTeklifFisiSaklamaYeri.text")); // NOI18N
        lblTeklifFisiSaklamaYeri.setName("lblTeklifFisiSaklamaYeri"); // NOI18N

        txtTeklifFisiSaklamaYeriAdi.setText(resourceMap.getString("txtTeklifFisiSaklamaYeriAdi.text")); // NOI18N
        txtTeklifFisiSaklamaYeriAdi.setName("txtTeklifFisiSaklamaYeriAdi"); // NOI18N

        btnKaydet.setText(resourceMap.getString("btnKaydet.text")); // NOI18N
        btnKaydet.setName("btnKaydet"); // NOI18N
        btnKaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKaydetActionPerformed(evt);
            }
        });

        btnListele.setText(resourceMap.getString("btnListele.text")); // NOI18N
        btnListele.setName("btnListele"); // NOI18N
        btnListele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListeleActionPerformed(evt);
            }
        });

        btnKapat.setText(resourceMap.getString("btnKapat.text")); // NOI18N
        btnKapat.setName("btnKapat"); // NOI18N
        btnKapat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKapatActionPerformed(evt);
            }
        });

        btnSil.setText(resourceMap.getString("btnSil.text")); // NOI18N
        btnSil.setName("btnSil"); // NOI18N
        btnSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSilActionPerformed(evt);
            }
        });

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        tblFizikselYer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblFizikselYer.setName("tblFizikselYer"); // NOI18N
        jScrollPane2.setViewportView(tblFizikselYer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTeklifFisiSaklamaYeri)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTeklifFisiSaklamaYeriAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnKaydet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnListele)
                        .addGap(18, 18, 18)
                        .addComponent(btnSil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnKapat)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTeklifFisiSaklamaYeri)
                    .addComponent(txtTeklifFisiSaklamaYeriAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKaydet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListele)
                    .addComponent(btnKapat)
                    .addComponent(btnSil))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKaydetActionPerformed
        // TODO add your handling code here:
        boolean sonuc;
        
        if(txtTeklifFisiSaklamaYeriAdi.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Lütfen Fiziksel Saklama Yer Giriniz");
            return;            
        }

        sql = "INSERT INTO public.fiziksel_yerler (yer, aktif) VALUES('" 
                + txtTeklifFisiSaklamaYeriAdi.getText() + "', 1)";

        try {
            sonuc = veriTabani.Guncelle(sql);
            if(sonuc == true)
            {
                JOptionPane.showMessageDialog(null, "Fiziksel Yer Başarılı Bir Şekilde Eklendi");
                
                txtTeklifFisiSaklamaYeriAdi.setText("");
                yonetimSistemi.TeklifFisiFizikselYerComboDoldur();
            }
            else
            {
                return;
            }
            
            btnListeleActionPerformed(evt);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_btnKaydetActionPerformed

    private void btnListeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListeleActionPerformed
        // TODO add your handling code here:
        
        sql = "select * from public.fiziksel_yerler WHERE aktif = 1";

        tblFizikselYer.setModel(DbUtils.resultSetToTableModel(veriTabani.Getir(sql)));

        tblFizikselYer.getColumnModel().getColumn(tblFizikselYer.getColumnModel().getColumnIndex("id")).setMinWidth(0);
        tblFizikselYer.getColumnModel().getColumn(tblFizikselYer.getColumnModel().getColumnIndex("id")).setMaxWidth(0);

        tblFizikselYer.getColumnModel().getColumn(tblFizikselYer.getColumnModel().getColumnIndex("aktif")).setMinWidth(0);
        tblFizikselYer.getColumnModel().getColumn(tblFizikselYer.getColumnModel().getColumnIndex("aktif")).setMaxWidth(0);
    }//GEN-LAST:event_btnListeleActionPerformed

    private void btnSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSilActionPerformed
        // TODO add your handling code here:
        String sql;
        String id;
        boolean sonuc;

        if(tblFizikselYer.getRowCount() == 0){
            JOptionPane.showMessageDialog(null, "Silinebilecek Bir Fiziksel Saklamı Yeri Yoktur!");
            return;
        }

        if(veriTabani.TabloSeciliMi(tblFizikselYer) == false){
            JOptionPane.showMessageDialog(null, "Lütfen Bir Fiziksel Saklamı Yeri Seçiniz!");
            return;
        }

        id = tblFizikselYer.getValueAt(tblFizikselYer.getSelectedRow(), tblFizikselYer.getColumnModel().getColumnIndex("id")).toString();
        sql = "UPDATE public.fiziksel_yerler SET aktif = 0 WHERE id = " + id;

        sonuc = veriTabani.Guncelle(sql);

        if (sonuc == true){
            JOptionPane.showMessageDialog(null, "Fiziksel Saklamı Yeri Başarılı Bir Şekilde Silinmiştir");
        }
        
        btnListeleActionPerformed(evt);
    }//GEN-LAST:event_btnSilActionPerformed

    private void btnKapatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKapatActionPerformed
        // TODO add your handling code here: Ekranı Kapatır. Deneme Yapılıyor. Kapattık ulen.
        
        veriTabani.BaglantiyiKapat();

        if(yonetimSistemi != null)
        {
            yonetimSistemi.enable(true);
            this.setVisible(false);
            yonetimSistemi.FizikselYerKapat();
            return;
        }

        System.exit(0);
    }//GEN-LAST:event_btnKapatActionPerformed

    public void SetYonetimSistemi(YonetimSistemi _yonetimSistemi){
        yonetimSistemi = _yonetimSistemi;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FizikselYer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FizikselYer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FizikselYer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FizikselYer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FizikselYer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKapat;
    private javax.swing.JButton btnKaydet;
    private javax.swing.JButton btnListele;
    private javax.swing.JButton btnSil;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblTeklifFisiSaklamaYeri;
    private javax.swing.JTable tblFizikselYer;
    private javax.swing.JTextField txtTeklifFisiSaklamaYeriAdi;
    // End of variables declaration//GEN-END:variables
}
